### PR TITLE
Fixed: Ctrl-C key press does not stop server

### LINKED ISSUE #328: Need to KeyboardInterrupt 3 times to stop the server
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**
I am trying out cheroot for the first time today. When I run my flask application with cheroot, I find that to stop the application, I need to hit `Ctrl+C` 3 times - even if I wait for nearly 2-3 minutes and no requests are being processed.

❓ **What is the motivation / use case for changing the behavior?**
It intuitively stop if I hit the Ctrl+C once I think ?

💡 **To Reproduce**
```
$ mkdir -p /tmp/cheroottesting
$ cd /tmp/cheroottesting
$ python -m venv venv
$ venv/bin/pip install cheroot
$ cat app.py
from wsgiref.simple_server import make_server

def application(environ, start_response):
    status = '200 OK'
    response_headers = [('Content-type', 'text/plain')]
    start_response(status, response_headers)
    return [b"Hello World !"]
$ export PYTHONPATH=.
$ venv/bin/cheroot app:application -b 0.0.0.0:5000
```
What I observe:
untitled

Note: I have tried to wait for about 30sec after hitting Ctrl-C for it to complete cleaning up after itself, didnt help much

💡 **Expected behavior**
The server should have stopped after I hit the first Ctrl-C

📋 **Details**
```
$ venv/bin/cheroot app:application --bind 0.0.0.0:5000

^CKeyboard Interrupt: shutting down


^CTraceback (most recent call last):
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/server.py", line 1710, in safe_start
    self.start()
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/server.py", line 1819, in start
    self.serve()
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/server.py", line 1798, in serve
    self.tick()
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/server.py", line 2038, in tick
    conn = self._connections.get_conn()
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/connections.py", line 137, in get_conn
    in self._selector.select(timeout=0.01)
  File "/home/abdealijk/miniconda3/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv/bin/cheroot", line 10, in <module>
    sys.exit(main())
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/cli.py", line 241, in main
    raw_args._wsgi_app.server(raw_args).safe_start()
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/server.py", line 1715, in safe_start
    self.stop()
  File "/tmp/cheroottesting/venv/lib/python3.7/site-packages/cheroot/server.py", line 2071, in stop
    time.sleep(0.1)
KeyboardInterrupt


^CException ignored in: <module 'threading' from '/home/abdealijk/miniconda3/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/home/abdealijk/miniconda3/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt
```

📋 **Environment**
- Cheroot version: 8.4.5
- CherryPy version: Not using it
- Python version: 3.7.7
- OS: Windows 10 + Ubuntu 18.04.4 LTS in WSL2
- Browser: Not applicable

📋 **Additional context**
Maybe this is related to: https://github.com/cherrypy/cheroot/issues/323

### PR DESCRIPTION
**Pull request by marc1n**
❓ **What kind of change does this PR introduce?**
  - [X] 🐞 bug fix

📋 **What is the related issue number (starting with `#`)**

Fixes #328
Fixes cherrypy/cherrypy#1873

❓ **What is the current behavior?** (You can also link to an open issue here)

Ctrl-C key press does not stop server

❓ **What is the new behavior (if this is a feature change)?**

Ctrl-C key press does stop server

📋 **Other information**:

---
This change is [Reviewable](https://reviewable.io/reviews/cherrypy/cheroot/322)

### CODE REVIEW

**Comment by webknjaz** [comment]
Hey @liamstask, were you the last person to refactor this? Could to take a look?

@marc1n thanks for the PR. Is there any way to add tests for this behavior?

**Comment by marc1n** [comment]
In Cheroot 8.5.0 Ctrl-C does not stop the server again...

**Comment by webknjaz** [comment]
Can it be that it's a different bug?

**Comment by marc1n** [comment]
@webknjaz It seems very similar: not setting `self._serving` to `False` in case of `KeyboardInterrupt` exception in function `cheroot.connections.ConnectionManager.run`

**Comment by liamstask** [comment]
ugh yes - i would have expected the existing ctrlc test to cover this, but the implementation changed in such a way that it no longer covered this case.

proposed fix in https://github.com/cherrypy/cheroot/pull/350

**Pull request merged**
