### PR TITLE
Fade to black

### PR DESCRIPTION
**Pull request by webknjaz**
* **What kind of change does this PR introduce?**
  - [ ] bug fix
  - [ ] feature
  - [ ] docs update
  - [ ] tests/coverage improvement
  - [x] refactoring
  - [x] other

* **What is the related issue number (starting with `#`)**

N/A

* **What is the current behavior?** (You can also link to an open issue here)

N/A

* **What is the new behavior (if this is a feature change)?**

black style enforced

* **Other information**:
@jaraco here's an idea of adopting black. I'm seeking on feedback, but in general, we would benefit, because contributors won't have to address style quirks, without having to figure out how to manually adjust style.

* **Checklist**:

  - [x] I think the code is well written
  - [x] I wrote [good commit messages][1]
  - [ ] I have [squashed related commits together][2] after the changes have been approved
  - [x] Unit tests for the changes exist
  - [ ] Integration tests for the changes exist (if applicable)
  - [x] I used the same coding conventions as the rest of the project
  - [x] The new code doesn't generate linter offenses
  - [ ] Documentation reflects the changes
  - [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences

[1]: http://chris.beams.io/posts/git-commit/
[2]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

---
This change is [Reviewable](https://reviewable.io/reviews/cherrypy/cheroot/103)

### CODE REVIEW

**Comment by jaraco** [comment]
meh. Some style changes are good. Other ones are removing meaningful or useful styling. But I guess we should practice deferring to our robot overlords. Do what you like.

**Comment by webknjaz** [comment]
> Other ones are removing meaningful or useful styling.

Yeah, that's what I'm worried about. At least I've disabled this annoying double-quoting of everything and adjusted line-length to PEP8 standard.

**Comment by jaraco** [comment]
I've found that selectively adopting a style system is sometimes worse than not using one at all. Then you have to manage the exclusions/selections plus each user to the project has to know what those are. I've never been a huge fan of flake8 or pep8, but the linter has protected me from many coding errors, which is why I've adopted it. I don't see that black will provide those same benefits. Maybe consider applying black just the once - and cherry-pick the patches to exclude. Then at least the styling will be generally consistent (and provide a template for others working on the project), but we don't have to apply it continuously or enforce violations of it.

**Comment by webknjaz** [comment]
Well, I like 99% of changes, so I think I'm +1 for keeping it.

**Comment by jaraco** [comment]
The consensus is rising on black. I'm happy to adopt it in cheroot/cherrypy too.

**Comment by webknjaz** [comment]
@jaraco I'm still unhappy with certain changes it does. I'm not ready to accept diff-unfriendly changes and I don't like that it does it wholesale (breaking Git blame at least).
I think, style should be chosen consciously by the human author, who knows _why_ they choose to use a certain way of writing those code lines.

**Comment by jaraco** [comment]
So I merged this branch with master, deferring to master for any conflicts, then re-ran `tox -e pre-commit` to re-black the code, but even after, the tests now fail PEP257 and flake8 hooks. I think that outcome reveals at least two issues with this approach.

**Comment by webknjaz** [comment]
I don't like black style after all.

**Pull request closed without merging**
