### PR TITLE
Avoid ssl alert bad certificate error from ssl clients

### PR DESCRIPTION
**Pull request by nizamial09**
This commit is to avoid the alert bad certificate error that keeps happening when some requests.

Signed-off-by: Nizamudeen A <nia@redhat.com>

❓ **What kind of change does this PR introduce?**
  - [x] 🐞 bug fix
  - [ ] 🐣 feature
  - [ ] 📋 docs update
  - [ ] 📋 tests/coverage improvement
  - [ ] 📋 refactoring
  - [ ] 💥 other

📋 **What is the related issue number (starting with `#`)**

#347

❓ **What is the current behavior?** (You can also link to an open issue here)

❓ **What is the new behavior (if this is a feature change)?**

📋 **Other information**:

📋 **Checklist**:

  - [ ] I think the code is well written
  - [ ] I wrote [good commit messages][1]
  - [ ] I have [squashed related commits together][2] after the changes have been approved
  - [ ] Unit tests for the changes exist
  - [ ] Integration tests for the changes exist (if applicable)
  - [ ] I used the same coding conventions as the rest of the project
  - [ ] The new code doesn't generate linter offenses
  - [ ] Documentation reflects the changes
  - [ ] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences

[1]: http://chris.beams.io/posts/git-commit/
[2]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

---
This change is [Reviewable](https://reviewable.io/reviews/cherrypy/cheroot/348)

### CODE REVIEW

**Review by webknjaz — CHANGES_REQUESTED** [review]
This needs a test and it shouldn't generate linter offenses.

**Comment by webknjaz** [comment]
@nizamial09 the commit is not linked to your GitHub account. You need to either add the committer email to GitHub or fix your local Git setup.

**Comment by nizamial09** [comment]
> @nizamial09 the commit is not linked to your GitHub account. You need to either add the committer email to GitHub or fix your local Git setup.
> 
> Also, fill out the PR template. It doesn't have any explanation currently.

Okay. I'll take care of that and will update it.

**Comment by webknjaz** [comment]
I'll mark it as a draft until ready

**Comment by nizamial09** [comment]
I couldn't reproduce this.

**Pull request closed without merging**
