### PR TITLE
 SSL `error: [Errno 0] Error` is present also on Python 3.7

### PR DESCRIPTION
**Pull request by Safihre**
❓ **What kind of change does this PR introduce?**
  - [x] 🐞 bug fix
  - [ ] 🐣 feature
  - [ ] 📋 docs update
  - [ ] 📋 tests/coverage improvement
  - [ ] 📋 refactoring
  - [ ] 💥 other

📋 **What is the related issue number (starting with `#`)**

https://github.com/cherrypy/cherrypy/issues/1618

❓ **What is the current behavior?** (You can also link to an open issue here)

https://github.com/cherrypy/cherrypy/issues/1618
Error is still present with Python 3.7.2, as reported by users on Windows and Linux machines.

❓ **What is the new behavior (if this is a feature change)?**

Always suppress this error.

📋 **Other information**:

📋 **Checklist**:

  - [x] I think the code is well written
  - [x] I wrote [good commit messages][1]
  - [x] I have [squashed related commits together][2] after the changes have been approved
  - [ ] Unit tests for the changes exist
  - [ ] Integration tests for the changes exist (if applicable)
  - [x] I used the same coding conventions as the rest of the project
  - [x] The new code doesn't generate linter offenses
  - [ ] Documentation reflects the changes
  - [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences

[1]: http://chris.beams.io/posts/git-commit/
[2]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

---
This change is [Reviewable](https://reviewable.io/reviews/cherrypy/cheroot/180)

### CODE REVIEW

**Comment by Safihre** [comment]
Is there a chance for an update on this one?

**Comment by webknjaz** [comment]
It would be nice to have some reproducible testcases for this...

**Comment by Safihre** [comment]
I think it can be reproduced with Selenium and Chrome, but that's a big additional test load.

**Comment by webknjaz** [comment]
@Safihre it's fine. It could go to cron job without being executed each time. I suspect that it might be connected to TLS 1.3 and maybe ciphers mismatch...

**Comment by webknjaz** [comment]
TCPdump/Wireshark dump may be useful for analysis...

**Pull request merged**
