### PR TITLE
Update type stubs to let `stubtest` succeed under Python 3.11

### LINKED ISSUE #567: pre-commit fails locally on Python 3.11 macOS
Running `tox -e pre-commit` fails in the mypy stubs check:

```
MyPy stubtest................................................................Failed
- hook id: stubtest
- exit code: 1

error: cheroot.ssl.Adapter is inconsistent, metaclass differs
Stub: at line 4 in file /Users/jaraco/code/cherrypy/cheroot/cheroot/ssl/__init__.pyi
N/A
Runtime: at line 6 in file /Users/jaraco/code/cherrypy/cheroot/cheroot/ssl/__init__.py
<class 'abc.ABCMeta'>

error: cheroot.ssl.builtin.BuiltinSSLAdapter is inconsistent, metaclass differs
Stub: at line 6 in file /Users/jaraco/code/cherrypy/cheroot/cheroot/ssl/builtin.pyi
N/A
Runtime: at line 139 in file /Users/jaraco/code/cherrypy/cheroot/cheroot/ssl/builtin.py
<class 'abc.ABCMeta'>

error: cheroot.ssl.pyopenssl.pyOpenSSLAdapter is inconsistent, metaclass differs
Stub: at line 25 in file /Users/jaraco/code/cherrypy/cheroot/cheroot/ssl/pyopenssl.pyi
N/A
Runtime: at line 241 in file /Users/jaraco/code/cherrypy/cheroot/cheroot/ssl/pyopenssl.py
<class 'abc.ABCMeta'>

error: cheroot.test failed to find stubs
Stub:
MISSING
Runtime:
<module 'cheroot.test' from '/Users/jaraco/code/cherrypy/cheroot/cheroot/test/__init__.py'>

error: cheroot.test.conftest failed to find stubs
Stub:
MISSING
Runtime:
N/A

error: cheroot.test.helper failed to find stubs
Stub:
MISSING
Runtime:
N/A

error: cheroot.test.test__compat failed to find stubs
Stub:
MISSING
Runtime:
N/A

error: cheroot.test.test_cli failed to find stubs
Stub:
MISSING
Runtime:
N/A

error: cheroot.test.test_conn failed to find stubs
Stub:
MISSING
Runtime:
N/A

error: cheroot.test.test_core failed to find stubs
Stub:
MISSING
Runtime:
N/A

error: cheroot.test.test_dispatch failed to find stubs
Stub:
MISSING
Runtime:
N/A

error: cheroot.test.test_errors failed to find stubs
Stub:
MISSING
Runtime:
N/A

error: cheroot.test.test_makefile failed to find stubs
Stub:
MISSING
Runtime:
N/A

error: cheroot.test.test_server failed to find stubs
Stub:
MISSING
Runtime:
N/A

error: cheroot.test.test_ssl failed to find stubs
Stub:
MISSING
Runtime:
N/A

error: cheroot.test.test_wsgi failed to find stubs
Stub:
MISSING
Runtime:
N/A

error: cheroot.test.webtest failed to find stubs
Stub:
MISSING
Runtime:
N/A

error: cheroot.testing failed to find stubs
Stub:
MISSING
Runtime:
N/A

Found 18 errors (checked 30 modules)

pylint.......................................................................Passed
Verify that enforced flake8 version stays unchanged..........................Passed
```

### PR DESCRIPTION
**Pull request by kasium**
❓ **What kind of change does this PR introduce?**

* [X] 🐞 bug fix
* [ ] 🐣 feature
* [ ] 📋 docs update
* [ ] 📋 tests/coverage improvement
* [ ] 📋 refactoring
* [ ] 💥 other

📋 **What is the related issue number (starting with `#`)**

Resolves #567

❓ **What is the current behavior?** (You can also link to an open issue here)
stubtest fails with a bunch of errors

❓ **What is the new behavior (if this is a feature change)?**
subtest doesn't fail anymore

- - -
This change is [Reviewable](https://reviewable.io/reviews/cherrypy/cheroot/568)

### CODE REVIEW

**Comment by kasium** [comment]
@webknjaz I get an weird error: https://github.com/cherrypy/cheroot/actions/runs/3504857916/jobs/5870808424

**Comment by webknjaz** [comment]
@kasium disregard that check, it's broken for PRs. I need to remake it.

**Comment by webknjaz** [comment]
@kasium but this error is legit: https://github.com/cherrypy/cheroot/actions/runs/3504857918/jobs/5870815679#step:12:51

**Comment by kasium** [comment]
As far as I can see a pretty old mypy version is used e.g. in `tox-pre-commit-cp39-linux-x86_64.txt`. This might be the issue now.
Should I regenerate the files somehow with the command listed inside?

However, I could also tell stubtest to ignore unused ignores

**Comment by webknjaz** [comment]
You could try re-generating one file and see what happens. Usually, an automated workflow tries to update the pins to the highest possible versions but sometimes something in the deptree would prevent that.
OTOH, pre-commit's mypy hooks don't rely on those pin files at all because pre-commit doesn't allow this type of pinning. So this will not change anything. It uses what's specified in `.pre-commit-config.yaml`.

**Comment by kasium** [comment]
So in the log I've seen mypy 0.931 used therefore my idea

**Comment by webknjaz** [comment]
> So in the log I've seen mypy 0.931 used therefore my idea

Ah, you're right. I forgot that this hook doesn't run on the pre-commit.ci service and only runs in GHA, relying on the surrounding toxenv. Looks like 2 constraint files are using the older version while only one uses the newer. Maybe it's worth it to update the constraints after all.

**Comment by webknjaz** [comment]
Note that the constraints file used in CI currently is 3.10, not 3.9. But it'd be reasonable to do this for all of 3.9-3.11, maybe.

**Comment by kasium** [comment]
@webknjaz seems like a test is flaky, isn't it?

**Comment by webknjaz** [comment]
Yes, there may be flaky tests. Also, I see that you've regenerated the constraints using Python 3.11 but each file is expected to be generated under its corresponding Python version, they shouldn't be the same.

**Comment by kasium** [comment]
@webknjaz I regenerated the files with the correct version

**Comment by webknjaz** [comment]
> Also no clue why the "commit body is empty" violation pops up

I've updated the linting to use the `gitlint` tool instead of the broken action. That rule hints that the commit messages you have only consist of titles but don't have extended bodies.

**Comment by webknjaz** [comment]
@kasium is it more evident here https://github.com/cherrypy/cheroot/actions/runs/3526229756#summary-9649152648 ?

**Comment by webknjaz** [comment]
@kasium have you checked that it succeeds under each Python version that the constraints files exist for? Our CI only runs under one version currently (maybe I'll need to change that :thinking:)

**Comment by kasium** [comment]
@webknjaz sorry I had not time to do that. Feel free to take this over (since I'm short on time)

**Review by webknjaz — APPROVED** [review]

**Pull request merged**
